base:
  project: mlops
  random_state: 42
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance_clean.csv

split_data:
  train_path: data/processed/insurance_train.csv
  test_path: data/processed/insurance_test.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 1.0
      l1_ratio: 0.5
      
model_path: models/models.joblib

reports:
  params: reports/params.json
  score: reports/scores.json